spring:
  application:
   name: flow-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/flowmanager2
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1


  cache:
    type: redis
    redis:
      time-to-live: ${app.subscription.cache-ttl-minutes:30}m
      cache-null-values: false
      key-prefix: "flow-manager:"
      use-key-prefix: true


  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false
    default-schema: public

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      acks: all
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

app:
  kafka:
    group-id: flow-manager-group
    topics:
      to-convert: to-convert
      conversion-responses: file-conversion-responses
      subscription-changed: subscription-changed

  subscription:
    free-file-size-limit-bytes: 104857600          # 100 МБ = 100 * 1024 * 1024
    cache-ttl-minutes: 30                          # сколько держать кеш в Redis


  scheduler:
    process-pending:
      fixed-delay: 5000
    retry-failed:
      fixed-delay: 60000
    clean-old-events:
      cron: "0 0 3 * * *"

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: conversion-files



server:
  port: 8082

eureka:
  client:
    service-url:

      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true          # ← использовать IP вместо hostname
    ip-address: 127.0.0.1            # ← явно указать localhost
    instance-id: ${spring.application.name}:${server.port}